services:
  api:
    build: .
    container_name: resource_api
    restart: always
    env_file:
      - .env.docker  
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
